Improve snapshot workflow

diff --git a/.github/workflows/snapshot.yml b/.github/workflows/snapshot.yml
--- a/.github/workflows/snapshot.yml
+++ b/.github/workflows/snapshot.yml
@@ -13,8 +13,11 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      - name: Check version
+        run: test -n ${{ github.event.client_payload.version }} || (echo "Missing snapshot version" && exit 1)
+
       - name: Build image
-        run: docker build -t banzaicloud/pipeline:${{ github.event.client_payload.version }} .
+        run: docker build -t banzaicloud/pipeline:${{ github.event.client_payload.version }} --build-arg VERSION=${{ github.event.client_payload.version }} .
 
       - name: Log into registry
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
